apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: eggplant-server
  namespace: exercise
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: app/v1
    kind: Deployment
    name: eggplant-server
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 60